BDAS2_DvorakovaKahounova/Controllers/ChovateleController.cs
using BDAS2_DvorakovaKahounova.DataAcessLayer;
using BDAS2_DvorakovaKahounova.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Oracle.ManagedDataAccess.Client;
using System.Data;
using System.Reflection;

namespace BDAS2_DvorakovaKahounova.Controllers
{
	public class ChovateleController : Controller
	{
		private readonly ChovateleDataAccess _dataAccess;

		public ChovateleController(IConfiguration configuration)
		{
			string connectionString = configuration.GetConnectionString("OracleConnection");
			_dataAccess = new ChovateleDataAccess(connectionString);
		}

		public IActionResult Index()
		{
			int uzivatelID = GetLoggedInUserId();
			if (uzivatelID == 0)
			{
				return RedirectToAction("Login", "Osoba"); // Pokud není uživatel přihlášen
			}
			List<Pes> psi = new List<Pes>();

			try
			{
				psi = _dataAccess.GetAllPsiProChovatele();
			}
			catch (Exception)
			{
				TempData["Message"] = "chyba při načítání psů.";
			}

			var originallRole = HttpContext.Session.GetString("OriginalRole");
			ViewData["IsAdmin"] = (User.Identity.IsAuthenticated && (originallRole == "A" || User.IsInRole("A")));

			return View(psi);

		}
		public IActionResult PridatPsa()
		{
			int uzivatelID = GetLoggedInUserId();
			if (uzivatelID == 0)
			{
				return RedirectToAction("Login", "Osoba"); // Pokud není uživatel přihlášen
			}

			if (User.Identity.IsAuthenticated && User.IsInRole("C"))
			{

				var originallRole = HttpContext.Session.GetString("OriginalRole");
				ViewData["IsAdmin"] = (User.Identity.IsAuthenticated && (originallRole == "A" || User.IsInRole("A")));

				return View(); // Zobrazí stránku rezervací
			}

			// Pokud podmínky nejsou splněny, přesměruje uživatele na přihlášení
			return RedirectToAction("Login", "Osoba");
		}

		public IActionResult VyriditAdopci(int pesId)
		{
			int uzivatelID = GetLoggedInUserId();
			if (uzivatelID == 0)
			{
				return RedirectToAction("Login", "Osoba"); // Pokud není uživatel přihlášen
			}

			if (User.Identity.IsAuthenticated && User.IsInRole("C"))
			{
				PesMajitelModel model = new PesMajitelModel();
				model.Pes = new Pes();
				model.Pes.ID_PSA = pesId;
				var originallRole = HttpContext.Session.GetString("OriginalRole");
				ViewData["IsAdmin"] = (User.Identity.IsAuthenticated && (originallRole == "A" || User.IsInRole("A")));

				return View(model); // Zobrazí stránku 
			}

			// Pokud podmínky nejsou splněny, přesměruje uživatele na přihlášení
			return RedirectToAction("Login", "Osoba");
		}

		[HttpPost]
		public IActionResult PridatOdcerveniAkce(int pesId, DateTime datumOdcerveni)
		{
			int uzivatelID = GetLoggedInUserId();
			if (uzivatelID == 0)
			{
				return RedirectToAction("Login", "Osoba"); // Pokud není uživatel přihlášen
			}
			try
			{
				// Zavolání metody PridatOdcerveni, která přidá odčervení pro konkrétního psa
				_dataAccess.PridatOdcerveni(pesId, datumOdcerveni);
				TempData["Message"] = "Záznam o odčervení úspěšně přidán";
			}
			catch (Exception)
			{
				TempData["Message"] = "Záznam o odčervení se nepřidal";
			}
			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult PridatOckovaniAkce(int pesId, DateTime datumOckovani)
		{
			int uzivatelID = GetLoggedInUserId();
			if (uzivatelID == 0)
			{
				return RedirectToAction("Login", "Osoba"); // Pokud není uživatel přihlášen
			}
			try
			{
				// Zavolání metody PridatOdckovani, která přidá očkování pro konkrétního psa
				_dataAccess.PridatOckovani(pesId, datumOckovani);
				TempData["Message"] = "Záznam o očkování úspěšně přidán";
			}
			catch (Exception)
			{
				TempData["Message"] = "Záznam o očkování se nepřidal";
			}

			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult ZaznamenatUmrti(int pesId)
		{
			try
			{
				_dataAccess.ZaznamenatUmrti(pesId);
				TempData["Message"] = "Úmrtí bylo úspěšně zaznamenáno.";
			}
			catch (Exception ex)
			{
				TempData["ErrorMessage"] = "Chyba při zaznamenávání úmrtí: ";
			}

			return RedirectToAction("Index");
		}


		public IActionResult ShowOwnerProfile(int ownerId)
		{
			return RedirectToAction("Profile", "Osoba", new { userId = ownerId });
		}

		//Fotografie
		public IActionResult UploadImage(int pesId, IFormFile imageFile)
		{
			if (imageFile != null && imageFile.Length > 0)
			{
				using (var stream = new MemoryStream())
				{
					imageFile.CopyTo(stream);
					var fotografie = new Fotografie
					{
						nazev_souboru = imageFile.FileName,
						typ_souboru = imageFile.ContentType,
						pripona_souboru = Path.GetExtension(imageFile.FileName),
						datum_nahrani = DateTime.Now,
						nahrano_id_osoba = GetLoggedInUserId(), // metoda pro získání ID přihlášeného uživatele
						obsah_souboru = stream.ToArray()
					};

					try
					{
						// Zavolání metody s transakcí
						_dataAccess.UpravFotografiiTransakci(fotografie, pesId);
					}
					catch (Exception ex)
					{
						TempData["Message"] = "Došlo k chybě při nahrávání fotografie.";
					}
				}
			}

			return RedirectToAction("Index"); // Po nahrání nebo úpravě fotografie se vrátíme na seznam psů
		}

		private int GetLoggedInUserId()
		{
			var userIdClaim = User.Claims.FirstOrDefault(c => c.Type == "UserId");
			if (userIdClaim != null)
			{
				return int.Parse(userIdClaim.Value);
			}
			return 0;
		}

		//Metody pro Pridat psa:


		[HttpPost]
		public IActionResult PridatPsa(string cisloCipu, string action, int[] vlastnosti, IFormFile fotografie)
		{
			int uzivatelID = GetLoggedInUserId();
			if (uzivatelID == 0)
			{
				return RedirectToAction("Login", "Osoba"); // Pokud není uživatel přihlášen
			}
			//vyhledání psa podle čísla čipu
			if (action == "search")
			{
				ViewBag.CisloCipu = cisloCipu;
				var idPsa = _dataAccess.GetPesIdByCisloCipu(cisloCipu);
				PesMajitelModel viewModel = new PesMajitelModel();
				if (idPsa.HasValue)
				{
					// Pokud je pes nalezen
					var pes = _dataAccess.ZobrazInfoOPsovi(idPsa.Value) ?? new Pes();
					var majitel = pes.ID_MAJITEL.HasValue
						? _dataAccess.GetUserProfileById(pes.ID_MAJITEL)
						: new Osoba();

					viewModel.Pes = pes;
					viewModel.Majitel = majitel;

					ViewData["Duvody"] = _dataAccess.GetDuvodyPobytu(); // Získání důvodů pobytu
				}
				else
				{
					// Pokud pes neexistuje, zobrazíme formulář pro přidání nového psa
					ViewBag.Message = "Pes nenalezen. Ujistěte se, že máte správně zadané číslo čipu. Pokud ano, zadejte údaje pro nového psa.";

					// Načítáme hodnoty pro comboboxy
					ViewData["Barvy"] = _dataAccess.GetBarvy();// Získání všech barev
					ViewData["Plemena"] = _dataAccess.GetPlemene();// Získání všech plemen
					ViewData["Duvody"] = _dataAccess.GetDuvodyPobytu(); // Získání důvodů pobytu
					ViewData["Vlastnosti"] = _dataAccess.GetVlastnosti(); // Získání všech vlastností
				}

				ViewBag.ShowForm = !idPsa.HasValue;

				var originallRole = HttpContext.Session.GetString("OriginalRole");
				ViewData["IsAdmin"] = (User.Identity.IsAuthenticated && (originallRole == "A" || User.IsInRole("A")));

				return View(viewModel);
			}
			else if (action == "nochip")
			{
				// Logika pro "Pes bez čipu"
				ViewData["Barvy"] = _dataAccess.GetBarvy();
				ViewData["Plemena"] = _dataAccess.GetPlemene();
				ViewData["Duvody"] = _dataAccess.GetDuvodyPobytu();
				ViewData["Vlastnosti"] = _dataAccess.GetVlastnosti(); // Získání všech vlastností
				ViewBag.ShowForm = true;
				ViewBag.Message = null;

				var originallRole = HttpContext.Session.GetString("OriginalRole");
				ViewData["IsAdmin"] = (User.Identity.IsAuthenticated && (originallRole == "A" || User.IsInRole("A")));

				return View(new PesMajitelModel());
			}
			//zadání nového psa do databáze
			else if (action == "createDog")
			{
				// Načtení hodnot z formuláře
				var jmeno = Request.Form["jmeno"];
				var cisloNovehoCipu = Request.Form["cisloCipu"];
				var datumNarozeni = string.IsNullOrEmpty(Request.Form["datumNarozeni"])
									? (DateTime?)null
									: DateTime.Parse(Request.Form["datumNarozeni"]);
				var barvaId = int.Parse(Request.Form["barva"]);
				var plemenoId = int.Parse(Request.Form["plemeno"]);
				var pohlaviId = int.Parse(Request.Form["pohlavi"]);
				var duvodPobytuId = int.Parse(Request.Form["duvodPobytu"]);
				var zacatekPobytu = DateTime.Parse(Request.Form["zacatekPobytu"]);
				var vaha = int.Parse(Request.Form["vaha"]);

				//////////////////////
				int? fotografieId = null;
				try
				{
					// Pokud je soubor fotografie přítomen, ulož ho

					if (fotografie != null && fotografie.Length > 0)
					{
						// Převeď soubor na byte[]
						using (var memoryStream = new MemoryStream())
						{
							fotografie.CopyTo(memoryStream);
							byte[] obsahFotografie = memoryStream.ToArray();

							// Vytvoř objekt Fotografie a nastav parametry
							var fotografieObj = new Fotografie
							{
								nazev_souboru = fotografie.FileName,
								typ_souboru = fotografie.ContentType,
								pripona_souboru = Path.GetExtension(fotografie.FileName),
								datum_nahrani = DateTime.Now,
								nahrano_id_osoba = GetLoggedInUserId(), // získání id přihlášeného uživatele
								obsah_souboru = obsahFotografie
							};

							// Ulož fotografii a získej ID
							fotografieId = _dataAccess.SaveFotografie(fotografieObj);
						}
					}
				}
				catch (Exception ex)
				{

					var originallllRole = HttpContext.Session.GetString("OriginalRole");
					ViewData["IsAdmin"] = (User.Identity.IsAuthenticated && (originallllRole == "A" || User.IsInRole("A")));

					// Ošetření chyby
					ViewBag.ErrorMessage = "Chyba při načítání fotografie.";
					return View();
				}
				////////////////////////

				try
				{
					_dataAccess.VlozNovehoPsa(jmeno, cisloNovehoCipu, datumNarozeni, plemenoId, barvaId, pohlaviId, fotografieId, vaha,
						zacatekPobytu, duvodPobytuId, vlastnosti);
				}
				catch (Exception ex) { ViewBag.ErrorMessage = "Chyba při vkládání psa do databáze."; }

BDAS2_DvorakovaKahounova/Views/Chovatele/Index.cshtml
@model List<BDAS2_DvorakovaKahounova.Models.Pes>

<div class="conteiner-chovatele">
	@if (TempData["Message"] != null)
	{
		<script>
			alert(@Html.Raw(Json.Serialize(TempData["Message"])));
		</script>
	}
	<table class="table-chovatele-vnejsi">
		@foreach (var pes in Model)
		{
			<tr>
				<!-- První buňka - Fotografie -->
				<td>

					@{
						string imageUrl = pes.ID_FOTOGRAFIE != null
						? Url.Action("GetImage", "Pes", new { id = pes.ID_FOTOGRAFIE })
						: Url.Action("DefaultImage", "Pes");
					}
					<img src="@imageUrl" alt="Fotka psa" style="width: 150px; height: auto;">
				</td>

				<!-- Druhá buňka - Nová tabulka pro informace o psu -->
				<td colspan="2">
					<table class="table-chovatele-vnitrni">
						<tr>
							<td><strong>Jméno:</strong></td>
							<td><strong>Číslo čipu:</strong></td>
							<td><strong>Datum narození:</strong></td>
							<td><strong>Pohlaví:</strong></td>
							<td><strong>Barva:</strong></td>
							<td><strong>Plemeno:</strong></td>
						</tr>
						<tr>
							<td>@(pes.JMENO ?? "Neznámé")</td>
							<td>@(string.IsNullOrEmpty(pes.CISLO_CIPU) ? "Pes bez čipu" : pes.CISLO_CIPU)</td>
							<td>@(pes.NAROZENI?.ToString("d") ?? "Neznámé")</td>

							<td>
								@if (pes.POHLAVI == 0)
								{
									<span>&male;</span>
								}
								else if (pes.POHLAVI == 1)
								{
									<span>&female;</span>
								}
								else
								{
									<span>Neznámé</span>
								}
							</td>
							<td>@pes.BARVA</td>
							<td>@pes.PLEMENO</td>

						</tr>

						<tr>
							<td><strong>Hmotnost (kg):</strong></td>
							<td><strong>Vlastnosti:</strong></td>
							<td><strong>Důvod pobytu:</strong></td>
							<td><strong>Krmná dávka (g):</strong></td>
							<td><strong>Majitel:</strong></td>
							<td><strong>Karanténa do:</strong></td>

						</tr>

						<tr>
							<td>@pes.VAHA.ToString("F1")</td>
							<td>@pes.VLASTNOSTI</td>
							<td>@pes.DUVOD_POBYTU</td>
							<td>@pes.KRMNA_DAVKA</td>
							<td>
								<a href="@Url.Action("ShowOwnerProfile", "Chovatele", new { ownerId = pes.ID_MAJITEL })">
									@pes.MAJITEL
								</a>
							</td>

							@if (@pes.KARANTENA_DO == null)
							{
								<td>Ukončena</td>
							}
							else
							{
								<td>@pes.KARANTENA_DO?.ToShortDateString()</td>
							}

						</tr>
					</table>
				</td>
			</tr>

			<tr>
				<td>
					<!-- Formulář pro nahrání nebo změnu fotografie -->

					<form asp-action="UploadImage" method="post" enctype="multipart/form-data">
						<input type="hidden" name="pesId" value="@pes.ID_PSA" />

						<!-- Skrytý input pro výběr souboru -->
						<input type="file" name="imageFile" accept="image/*" id="fileInput_@pes.ID_PSA" style="display: none;" @(pes.ID_FOTOGRAFIE != null ? "" : "required") />

						<!-- Tlačítko pro otevření dialogu pro výběr souboru -->
						<button type="button" class="btn btn-primary" onclick="document.getElementById('fileInput_@pes.ID_PSA').click();">
							@(pes.ID_FOTOGRAFIE != null ? "Upravit fotografii" : "Přidat fotografii")
						</button>

						<!-- Skript pro automatické odeslání formuláře po výběru souboru -->
						<script>
							document.getElementById('fileInput_@pes.ID_PSA').addEventListener('change', function () {
								if (this.files.length > 0) {
									this.form.submit(); // Po výběru souboru automaticky odeslat formulář
								}
							});
						</script>
					</form>

				</td>
				<td class="td-chovatele" colspan="2">

					<div class="button-chovatele">
						@if (@pes.ID_MAJITEL == null && @pes.REZERVOVANO == null)
						{
							<form asp-action="Adoptovat" method="post" class="button-form">
								<input type="hidden" name="pesId" value="@pes.ID_PSA" />
								<button class="btn btn-primary" type="submit">Vyřídit adopci</button>
							</form>
						}
						else if (pes.ID_MAJITEL != null)
						{
							<form asp-action="VyzvednoutMajitelem" method="post" class="button-form">
								<input type="hidden" name="pesId" value="@pes.ID_PSA" />
								<button class="btn btn-primary" type="submit">Vyzvednut majitelem</button>
							</form>
						}

						<button class="btn btn-primary" onclick="showDewormingForm(@pes.ID_PSA)">Přidat záznam o odčervení</button>


						<button class="btn btn-primary" onclick="showVaccinationForm(@pes.ID_PSA)">Přidat záznam o očkování</button>

						<form asp-action="ZaznamenatUmrti" method="post">
							<input type="hidden" name="pesId" value="@pes.ID_PSA" />
							<button class="btn btn-primary" type="submit">Zaznamenat úmrtí</button>
						</form>
					</div>
				</td>
			</tr>
			<tr>
				<td></td>
				<td style="width: 50%;">
					<div id="dewormingForm_@pes.ID_PSA" style="display: none; margin-top: 10px;">
						<form asp-action="PridatOdcerveniAkce" method="post">
							<input type="hidden" name="pesId" value="@pes.ID_PSA" />
							<label for="datumOdcerveni_@pes.ID_PSA">Datum odčervení:</label>
							<input type="date" id="datumOdcerveni_@pes.ID_PSA" name="datumOdcerveni" required class="form-control" />
							<button type="submit" class="btn btn-success" style="margin-top: 10px;">Uložit</button>
							<button type="button" class="btn btn-secondary" style="margin-top: 10px;" onclick="hideDewormingForm(@pes.ID_PSA)">Zrušit</button>
						</form>
					</div>
				</td>
				<td style="width: 50%;">
					<div id="vaccinationForm_@pes.ID_PSA" style="display: none; margin-top: 10px;">
						<form asp-action="PridatOckovaniAkce" method="post">
							<input type="hidden" name="pesId" value="@pes.ID_PSA" />
							<label for="datumOckovani_@pes.ID_PSA">Datum očkování:</label>
							<input type="date" id="datumOckovani_@pes.ID_PSA" name="datumOckovani" required class="form-control" />
							<button type="submit" class="btn btn-success" style="margin-top: 10px;">Uložit</button>
							<button type="button" class="btn btn-secondary" style="margin-top: 10px;" onclick="hideVaccinationForm(@pes.ID_PSA)">Zrušit</button>
						</form>
					</div>
				</td>
			</tr>
		}
	</table>

</div>

<script>
	function showDewormingForm(pesId) {
		document.getElementById(`dewormingForm_${pesId}`).style.display = 'block';
	}

	function hideDewormingForm(pesId) {
		document.getElementById(`dewormingForm_${pesId}`).style.display = 'none';
	}

	function showVaccinationForm(pesId) {
		document.getElementById(`vaccinationForm_${pesId}`).style.display = 'block';
	}

	function hideVaccinationForm(pesId) {
		document.getElementById(`vaccinationForm_${pesId}`).style.display = 'none';
	}
</script>

BDAS2_DvorakovaKahounova/Views/Chovatele/VyriditAdopci.cshtml
@model BDAS2_DvorakovaKahounova.Models.PesMajitelModel

@{
    ViewData["Title"] = "VyriditAdopci";
}

<h1>Vyřídit Adopci</h1>

<div class="input-container-rezervace">
	<form method="post">
		<input type="hidden" name="idPes" value="@Model.Pes.ID_PSA" />
		<input type="text" id="email" name="email" value="@ViewBag.Email"
			   required placeholder="Zadejte email žadatele o adopci"
			   @* oninput="this.setCustomValidity('')" *@ /><p></p>
		<button type="submit" class="btn-rezervace" name="action" value="search">Vyhledat</button>
	</form>
</div>

<div class="info-majitel">
@if (@Model?.Majitel?.EMAIL != null)
{
	<p><strong>Majitel:</strong> @Model.Majitel.JMENO @Model.Majitel.PRIJMENI</p>

		<div class="container-profil3">
			<input type="checkbox" id="toggle-info" />
			<span class="eye" onclick="toggleVisibility()">
				<img src="~/images/eye-close.png" alt="Eye Icon" class="eye-icon">
			</span> <!-- Symbol pro oko -->
			<span class="eye-slash" onclick="toggleVisibility()">
				<img src="~/images/eye.png" alt="Eye Icon" class="eye-icon">
			</span> <!-- Symbol pro oko se škrtnutím -->
		</div>
		
		<div id="info-container">
			<p><strong>Email: </strong><span id="email2" style="display:none;">@Model.Majitel.EMAIL</span></p>
			<p><strong>Telefon: </strong><span id="telefon" style="display:none;">@Model.Majitel.TELEFON</span></p>
		</div>

		

	<form method="post">
		<input type="hidden" name="idPes" value="@Model.Pes.ID_PSA" />
		<input type="hidden" name="majitelIdOsoba" value="@Model.Majitel.ID_OSOBA" />
		<button type="submit" class="btn btn-primary" name="action" value="adoptovatPsa">Adoptovat psa</button>
	</form>
}
else if (ViewBag.ErrorMessage != null)
{
		<script type="text/javascript">
			alert('Osoba nenalezena. Žadatel o adopci se musí nejprve zaregistrovat.');
		</script>
		<a href="@Url.Action("Register", "Osoba")" class="btn btn-primary">Přejít k registraci</a>
}

</div>

<script>
	// Funkce pro přepínání zobrazení informací
	function toggleVisibility() {
		var email2 = document.getElementById('email2');
		var telefon = document.getElementById('telefon');
		var eye = document.querySelector('.eye');
		var eyeSlash = document.querySelector('.eye-slash');

		// Pokud je "oko" zobrazené, skryjeme informace, jinak je zobrazíme
		if (email2.style.display === 'none' || telefon.style.display === 'none') {
			email2.style.display = 'inline';
			telefon.style.display = 'inline';
			eye.style.display = 'none'; // Skrýt "oko"
			eyeSlash.style.display = 'inline'; // Zobrazit "oko se škrtnutím"
		} else {
			email2.style.display = 'none';
			telefon.style.display = 'none';
			eye.style.display = 'inline'; // Zobrazit "oko"
			eyeSlash.style.display = 'none'; // Skrýt "oko se škrtnutím"
		}
	}
</script>